### ISSUE TITLE
Running sugar example does not work

### ISSUE THREAD

**Issue by SergeStinckwich** [tomooda/ReMobidyc#2]
When running ```RMDInterpreter exampleSugar```, a PP2Failure is generated, but ```RMDVisualizer exampleSugarScape``` works.

**Comment by tomooda** [comment]
now fixed by 48081f3f7c8bcffa728e9a26c9674f826e1cdc48

**Comment by tomooda** [comment]
Thank you pointing it out. It was very old code in an old syntax of Re:Mobidyc.
